### ISSUE TITLE
Start Project issues

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#23]
1. Move Website Design and Development to the top
2. Add Login back into the nav bar.  Should keep me on the same page after I login.

**Comment by davidkarn** [comment]
I moved the website section to the top, and made the login form load via ajax without requiring a page reload. If you login on the create a project survey page, it should fill in the form fields (if you haven't entered anything in them) with the defaults it would show if you were creating a project and already logged in.
