### ISSUE TITLE
Start Project Flow change

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#24]
NEW USERS:

1. Creates a user account automatically after user hit Get Started.  Password is defaulted and email sent with link to change it 
2. Change “Please describe your business.” to “Please describe your project” below Company Name
3. Add Project Name field to the right of Company Name field.  

EXISTING USERS:

1. Remove name and email from project fields
2. Add Project Name to the right of Company Name field
3. Change “Please describe your business.” to “Please describe your project”
4. Company name default to user’s company but editable
5. Target Audience and Keywords can default if they have entered it before.  Use last entry.

**Comment by jasonculbertson** [comment]
I see an error for existing users where it is using Company Name for Full Name instead of the user's name.  Can you fix this please?  Also, Full Name and Email should not be visible.  See attachment.

![screen shot 2015-01-14 at 10 52 45 pm](https://cloud.githubusercontent.com/assets/2825709/5753569/5d335da4-9c40-11e4-9b64-9671c34aad59.png)

**Comment by davidkarn** [comment]
Yea I was confused about the full name vs company name, all of these bullet points should be implemented and working on the live site now.
