### ISSUE TITLE
Password Sent confirmation

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#25]
I don't see a confirmation popup for Forgot Password.  Can you ensure that this was done?  User should have to click to leave the popup.  Should not go away on it's own.

![4_password_reset_sent](https://cloud.githubusercontent.com/assets/2825709/5728910/ff26d2ae-9b22-11e4-8703-81bc29356b2f.jpg)

**Comment by davidkarn** [comment]
I think the problem was it wasn't showing an error message when you entered an invalid email, it should be fixed now
