### ISSUE TITLE
Admin avatar on project page should be smiley face

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#28]
The avatar for the admin should be the smiley face chat.png.  Right now it seems that the system is showing the chat icon for admins and users then when a comment is made it changes.

For the user it should be their gravatar and for the admin the smiley face.  When they comment it doesn't change.

**Comment by davidkarn** [comment]
Updated the admin avatar, fixed the default gravatar not rendering, and made the current user's avatar show next to the message box
