### ISSUE TITLE
Admin should not see Pay Invoice

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#32]
The admin has no reason to see Pay Invoice.  Only user does.

Instead they should be able to add an invoice.  @nsgbento can you mock this up please?  Admin should be able to enter a dollar amount for the first and second invoice.  It will default an amount based upon what they picked for the project but it's something that they should be able to change.

**Comment by nsgbento** [comment]
That makes sense.  I will mock this up

**Comment by nsgbento** [comment]
![editclicked](https://cloud.githubusercontent.com/assets/10343797/5768295/5b43268a-9cc4-11e4-9d69-1806d563236f.png)
![normal](https://cloud.githubusercontent.com/assets/10343797/5768296/5b43fbd2-9cc4-11e4-9993-4acf59834fb2.png)

**Comment by jasonculbertson** [comment]
This is how the admin can change an invoice:

![screen shot 2015-01-21 at 12 28 27 pm](https://cloud.githubusercontent.com/assets/2825709/5844474/03055598-a169-11e4-96b1-7f75efe16ae1.png)



This is what it looks like if an invoice was paid:

![screen shot 2015-01-21 at 12 27 56 pm](https://cloud.githubusercontent.com/assets/2825709/5844468/f2ddbd7c-a168-11e4-8e81-1889fba930af.png)

**Comment by davidkarn** [comment]
This is running on the live site now
