### ISSUE TITLE
Admin Delete and Archive Project

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#33]
Admin should have additional links under Edit Project to Delete Project and Archive Project.  User should only see Edit Project.

**Comment by davidkarn** [comment]
Added archive and delete project

**Comment by jasonculbertson** [comment]
Working.  One issue.  If I archive a project I should be able to unarchive it. 

1. The text should read "Unarchive Project"
2. If clicked move it back to My Projects.

**Comment by davidkarn** [comment]
So if I unarchive it should it set the status to whatever it was before it was archived?

**Comment by jasonculbertson** [comment]
Yes.

On Tue, Jan 20, 2015 at 3:54 PM, David Karn <notifications@github.com>
wrote:

> So if I unarchive it should it set the status to whatever it was before it
> was archived?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UseBento/UseBento/issues/33#issuecomment-70759260>.
>



-- 
Jason Culbertson

**Comment by davidkarn** [comment]
Added unarchive
