### ISSUE TITLE
Pricing is wrong on services pages

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#35]
Go through and check all pricing.

**Comment by jasonculbertson** [comment]
Social Media: Each service should be $200.  Default of FB selected.

Presentation: Each slide $100

Stationary: $400

Business Card: $400

Landing Page:  
    Design Only : $650
    Design +Dev: $1050
    Responsive: $1200

HTML Page: 
    Design Only : $650
    Design +Dev: $1050
    Responsive: $1200

Wordpress Page:
    Design Only : $650
    Design +Dev: $1300
    Responsive: $1550

**Comment by davidkarn** [comment]
Updated all the prices and calculations

**Comment by jasonculbertson** [comment]
I forgot Email.  Sorry!!  

Design only : $350
Design and Dev: $500

**Comment by davidkarn** [comment]
updated email prices
