### ISSUE TITLE
Issue with new project page vertical line

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#37]
When a user is dropped into the project page for the first time there is a strange issue where the right vertical line is not going all the way down.  See screenshot.  It's the line to the right of Comment button.

![conversation](https://cloud.githubusercontent.com/assets/2825709/5772685/3fa8e544-9d0b-11e4-9f5f-9728f9f63b2f.png)

**Comment by jasonculbertson** [comment]
This seems to be fixed but now the border around the chat is gone.

**Comment by davidkarn** [comment]
The vertical line follows the messages box, not the sidebar. It looks like it's fixed now because now that a message is posted every time a project is created the messages section is longer than the sidebar. 

I'm not sure what border is supposed to show up around the chat though..

**Comment by jasonculbertson** [comment]
If you look at the screenshot at the beginning of this thread, there was a stroke around the container that had has the conversation in it.

**Comment by davidkarn** [comment]
Oh, duh. I re-added the border.

**Comment by jasonculbertson** [comment]
yeah!
