### ISSUE TITLE
Empty comment should not be able to post

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#38]
If a user hits the Comment button and didn't type anything it posts "Add a comment or upload a file..." into the comment thread.  They shouldn't be able to comment at all.  

1. If they don't upload a file or write something the comment button should be faded out 50% and not clickable.
2. If  they upload a file and click Comment then it should only show the file, not the text "Add a comment or upload a file..."

**Comment by davidkarn** [comment]
I replaced the add a comment or upload a file text with a placeholder in the textarea so it won't get submitted. I also set the submit button to disabled unless text or files have been entered and made disabled buttons show at 50% opacity

**Comment by jasonculbertson** [comment]
I don't see this working yet.  Did you push?

**Comment by davidkarn** [comment]
It's live now. There was a bug also where it wouldn't recognize that you entered text until the message box was blurred, I fix that too.
