### ISSUE TITLE
Autofill email and password for login

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#39]
Use cookies to be able to autofill email and password for returning users.

**Comment by davidkarn** [comment]
Autofill email makes sense but are you really sure about autofilling passwords? 

What if someone signs in on a public terminal or on another person's machine? They will be leaving their login details available even if they log out.

**Comment by jasonculbertson** [comment]
Ok. Makes sense. No autofill password.

**Comment by davidkarn** [comment]
added autofill for email address
