### ISSUE TITLE
Types of Projects layout on homepage is broken

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#40]
Looks broken to me.  Can you take a look.

**Comment by jasonculbertson** [comment]
I don't see anything wrong.  @nsgbento do you see the issue still?  Can you share screenshot?

**Comment by nsgbento** [comment]
![screen shot 2015-01-19 at 3 16 17 pm](https://cloud.githubusercontent.com/assets/10343797/5809511/2f835a92-9fee-11e4-89e0-7caffacdd0d7.png)

**Comment by nsgbento** [comment]
Still looks broken to me

**Comment by davidkarn** [comment]
What browser are you using where you see this behaviour? I'm trying on chrome and safari and firefox and the boxes move into two columns that are lined up appropriately as I resize the browser width. 

I did notice some weirdness with the labels (Banner Ads, HTML Emails...) that only pop up at a smaller resolution, on some browsers the text is cut off or spaced poorly. I can fix this but I'm wondering, are the text labels supposed to show up on all resolutions?

**Comment by nsgbento** [comment]
This is happening for me on Chrome - however it is working fine on Safari.  @jasonculbertson is this something that we want to punt on for now if its not even going to be apart of the new homepage design?

**Comment by jasonculbertson** [comment]
Let's not worry about it. Could be a plugin issue for your chrome.
