### ISSUE TITLE
The first time a client lands on the project page there is a welcome message from "Noah" (copy in comment)

### ISSUE THREAD

**Issue by nsgbento** [UseBento/UseBento#41]
Hi there!  My name is Noah and I'm your project manager.  Its my job to make sure your project gets done quickly and professionally.  If you have any questions just write them in the message field below and I'll get back to you ASAP. 

If you're ready to get your project started now, just pay your first invoice by clicking the "Pay Invoice Now" button on the right.  Looking forward to working with you and please let me know if you have any questions!

**Comment by davidkarn** [comment]
Changed admin name to noah and made this the first message posted on every new project
