### ISSUE TITLE
Add sorting to project list

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#49]
Add arrows next to header text so admin and user can sort projects by clicking on the column header text.

**Comment by davidkarn** [comment]
I implemented using the jquery tablesorter plugin. 

For the UI I'm adding an arrow to the side of the column being sorted to denote whether it is ASC or DESC and make the headers use cursor:pointer to show they can be sorted.

**Comment by jasonculbertson** [comment]
Can you move the carot closer to the word?  It's a bit confusing.  Thanks!

**Comment by davidkarn** [comment]
Moved to the immediate right of the column label
