### ISSUE TITLE
On the project page, datetime stamp all messages instead of "2 days ago"

### ISSUE THREAD

**Issue by nsgbento** [UseBento/UseBento#52]

**Comment by davidkarn** [comment]
Formatting message times as: Posted January 20th, 2015 22:52

**Comment by jasonculbertson** [comment]
What timezone?  Can you add PST or something?

**Comment by davidkarn** [comment]
I changed it to: 'Posted January 20th, 2015 3:36pm PST', with it always defaulting to PST
