### ISSUE TITLE
Change "What type of responsive development do you need?" text.

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#56]
Change "What type of responsive development do you need?" to "What do you want this optimized for?"

**Comment by jasonculbertson** [comment]
Updated.

**Comment by jasonculbertson** [comment]
Still not updated for Wordpress projects.

**Comment by davidkarn** [comment]
There was a stray copy of the _wordpress_design_and_development_form.html.slim in another folder that was superseding the changes made to the one in view/applications. It looks like removing this file fixed the issue
