### ISSUE TITLE
Change order of the Project List for Users

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#60]
Change the order and fields on project list for users to be:

1. Project Name
2. Project Type
3. Date Started
4. Last Updated (this is when a comment last happened ie. "2 hours ago")
5. Status

**Comment by davidkarn** [comment]
Is this meant to be for users only then (ie, the admin layout stays the same)?

**Comment by jasonculbertson** [comment]
Users only. Admin has a different view.

**Comment by davidkarn** [comment]
Ok makes sense. What about the last updated date? If a message is posted or file is uploaded should that bump up the last updated date for the project?

**Comment by jasonculbertson** [comment]
Any action is an "update"

**Comment by davidkarn** [comment]
I updated the order for users, left it the same for administrators, and made new messages update the 'last updated time'
