### ISSUE TITLE
Reset Password page styling

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#62]
Can you take the reset password page and style it using our existing fields and button style?  Currently it is unstyled.  See attached.  

Thanks!

![screen shot 2015-01-19 at 12 04 38 pm](https://cloud.githubusercontent.com/assets/2825709/5806991/659bba22-9fd3-11e4-84b5-6d58a253e664.png)

**Comment by jasonculbertson** [comment]
There is also a log in page that has the same issue.  

![screen shot 2015-01-22 at 4 42 05 pm](https://cloud.githubusercontent.com/assets/2825709/5867805/a3ef226c-a255-11e4-8346-2984ff34ffc6.png)

**Comment by davidkarn** [comment]
I updated these to look closer to the other forms on the site

**Comment by jasonculbertson** [comment]
This is looking good.  Is there a way center the fields?  Also, the header for Sign Up should look the same as Log In and also be centered.  Let me know if you need assistance with this?

**Comment by davidkarn** [comment]
I centered them and made the sign up page have the same header as the other user forms

**Comment by jasonculbertson** [comment]
I just updated the CSS so that this looks more centered.
