### ISSUE TITLE
Log In takes me to Project Page

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#63]
When I click log in at the top and sign in keeps me at the home page. I feel like if I have an active project then it should take me to the project dashboard to see all open projects.

**Comment by davidkarn** [comment]
I had it do this if you log in from the homepage. For the other pages I'm not sure if we want to redirect to the projects page because they might have entered data into the forms that would be lost.

**Comment by jasonculbertson** [comment]
This is perfect. Thanks!!
