### ISSUE TITLE
Address on checkout page?

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#67]
Do we have to have the address in the payment screen?  Was not originally supposed to be there.  Is the mandatory?  Also it's there for paypal too which does not make sense to me.

**Comment by davidkarn** [comment]
You can't receive a payment by card without a billing address. 

It could be moved to the credit card section though.

**Comment by jasonculbertson** [comment]
We only need it for CC.  So I would love for it to disappear for paypal.  I
guess move it under the CC info.

On Wed, Jan 28, 2015 at 9:24 AM, David Karn <notifications@github.com>
wrote:

> You can't receive a payment by card without a billing address.
>
> It could be moved to the credit card section though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UseBento/UseBento/issues/67#issuecomment-71876477>.
>



-- 
Jason Culbertson

**Comment by davidkarn** [comment]
I moved it to underneath the credit card inputs, and made the address fields required only if CC is selected
