### ISSUE TITLE
Remove percentage of payment total from checkout page

### ISSUE THREAD

**Issue by nsgbento** [UseBento/UseBento#68]
We dont need the percentage amount to be shown as seen in the screen shot

![screen shot 2015-01-27 at 2 06 15 pm](https://cloud.githubusercontent.com/assets/10343797/5928175/c4b9ee10-a62d-11e4-9a8e-53100e0d6a7d.png)

**Comment by davidkarn** [comment]
I just took out the % and replaced it with "Deposit" to try to make it clear that the payment they are paying is just the Deposit and not the Subtotal.
