### ISSUE TITLE
Project Total should be editable

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#69]
We are seeing an error where project total does not change when I change an invoice amount.  I think we realized that we need another line for Project Total and that if I change the project total amount it affects the invoices where it splits the price in two.  This should also work when I change an invoice price it should update the project total.  

This should change the project total in the top of the project page and also on the payment page.

![edit_invoice](https://cloud.githubusercontent.com/assets/2825709/5928403/e18ef11e-a62f-11e4-8ae4-0ed0cd065dde.jpg)

**Comment by davidkarn** [comment]
Added update total, and made project total and awaiting payment amounts update themselves automatically to be consistent with new changes.
