### ISSUE TITLE
Remove Start Project for admin

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#73]
On the project list page for admin, please remove Start a New Project button.  This is for admin only.

**Comment by davidkarn** [comment]
Removed the start a new project button for admins

**Comment by jasonculbertson** [comment]
I still see it there.
![screen shot 2015-01-28 at 9 46 59 pm](https://cloud.githubusercontent.com/assets/2825709/5953010/36dab9ca-a737-11e4-90c5-6833fd5dcbd7.png)
