### ISSUE TITLE
a filename with a dot in it breaks the image

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#77]
I uploaded a screenshot png and it wasn't showing.  Through trial and error we realized that a mac puts "dots" in the filename between dates and that was breaking the ability to attach a file.

You think this is solvable?  I can imagine screenshots being really important.

**Comment by davidkarn** [comment]
Fixed. Rails was getting confused by having more than one dot in the pathname because it reserved dots for file formats like /x.json .
