### ISSUE TITLE
Unarchiving a project broke admin project list view.

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#78]
When I unarchived a project it broke the project list view for admin.  Just shows me sorry something went wrong message.

Also noticed that when I archived it the first time the column titles did not match the admin view.  It was the column titles for the user.  Maybe that was part of the issue.

**Comment by davidkarn** [comment]
It wasn't related to the breaking the project page issue but I did make the archived projects list use the same columns as the open projects
