### ISSUE TITLE
Change name from "Info" to "Bento" when sending an email to a client from Bento

### ISSUE THREAD

**Issue by nsgbento** [UseBento/UseBento#80]
![screen shot 2015-01-27 at 4 37 38 pm](https://cloud.githubusercontent.com/assets/10343797/5930332/04cc1a22-a643-11e4-862e-93eb14b1530c.png)

**Comment by davidkarn** [comment]
Updated mailers to use Bento <info@usebento.com> as the address, or if the email is coming from the contact/apply forms, use the person's name and email. For project message emails, it should no longer be using the user's email address, but info@usebento.com.
