### ISSUE TITLE
Change email autofill from full name to just first

### ISSUE THREAD

**Issue by nsgbento** [UseBento/UseBento#81]
When a user gets an email from the admin its filling in their whole name instead of just the first name. We want just the first name and the comma to be in the right place.  You can see what Im talking about in the screen shot below

![screen shot 2015-01-27 at 4 50 02 pm](https://cloud.githubusercontent.com/assets/10343797/5930469/dd5dcc36-a644-11e4-8ca0-11b63899b0a4.png)

**Comment by davidkarn** [comment]
Using only the first name now. Since the name field isn't separated (users are asked to enter their full name when they sign up, instead of two separate fields), I'm just taking the part of their full name that comes before the first space and using that.

**Comment by nsgbento** [comment]
So the name issue is fixed but we still need to move the comma after the name because right now the comma is showing after hey

**Comment by davidkarn** [comment]
All emails should have the comma after the recipient's name now.
