### ISSUE TITLE
Slow loading of homepage

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#82]
The homepage is loading very slow as a result of the big header image.  Couple suggestions but leaving to @davidkarn to figure out.

1. On the big photo background, pick a color and set that to start, and have the photo hidden. When the photo finishes loading, change the background to the image and fade it in. 

2. Use a cloud caching service

**Comment by jasonculbertson** [comment]
A friend who is a developer mentioned that our images should load through something like Amazon cloudfront, as well as our CSS and JS.

**Comment by davidkarn** [comment]
Yea Amazon cloudfront would be a good idea. The size of that image can be reduced considerably if you can tolerate a little jpeg compression.

Right now the image is at 1.1mb, which is pretty huge for a web background.

This is it saved at jpeg quality 70, 228kb:

![desk-jpeg70](https://cloud.githubusercontent.com/assets/3698908/5953064/12de6322-a738-11e4-98ca-28bfc5b68a0c.jpg)

jpeg 62, 159kb:

![desk-62](https://cloud.githubusercontent.com/assets/3698908/5953073/4271c412-a738-11e4-9618-af4614f0b9d2.jpg)

jpeg 55, 125kb

![desk-55](https://cloud.githubusercontent.com/assets/3698908/5953077/4b0cf678-a738-11e4-82a6-a1cd10ca78d1.jpg)

The artifacting is most noticeable on the little orange book in the lower left, and to a lesser extent on the keyboard in the upper right. The rest of the image looks fine for the most part. Using the jpeg 55 version would cut the filesize down almost 10%.

**Comment by jasonculbertson** [comment]
Let’s do jpeg 55. That’s fine.

On Wed, Jan 28, 2015 at 9:58 PM, David Karn< notifications@github.com [notifications@github.com] > wrote:
Yea Amazon cloudfront would be a good idea. The size of that image can be
reduced considerably if you can tolerate a little jpeg compression.

Right now the image is at 1.1mb, which is pretty huge for a web background.

This is it saved at jpeg quality 70, 228kb:


https://cloud.githubusercontent.com/assets/3698908/5953064/12de6322-a738-11e4-98ca-28bfc5b68a0c.jpg

jpeg 62, 159kb:


https://cloud.githubusercontent.com/assets/3698908/5953073/4271c412-a738-11e4-9618-af4614f0b9d2.jpg

jpeg 55, 125kb


https://cloud.githubusercontent.com/assets/3698908/5953077/4b0cf678-a738-11e4-82a6-a1cd10ca78d1.jpg

The artifacting is most noticeable on the little orange book in the lower left,
and to a lesser extent on the keyboard in the upper right. The rest of the image
looks fine for the most part. Using the jpeg 55 version would cut the filesize
down almost 10%.

—
Reply to this email directly or view it on GitHub
[https://github.com/UseBento/UseBento/issues/82#issuecomment-71973166] .



Jason Culbertson

**Comment by davidkarn** [comment]
Replaced with the 62 image
