### ISSUE TITLE
Missing space below My Project in admin project list view

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#83]
See attached.  The space below My Projects is missing for some reason.

![screen shot 2015-01-30 at 10 17 26 am](https://cloud.githubusercontent.com/assets/2825709/5980857/6e4c9396-a869-11e4-8774-e25751a69fd3.png)

**Comment by davidkarn** [comment]
It looks like there needs to be content in the right section of the header where the start a new project button used to be. Filling it with &nbsp; fix the problem
