### ISSUE TITLE
Can't upload a file that is more then 14mb

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#85]
I just uploaded a 13.9mb pdf with no problem. Does not like a 19mb file that I am testing.  Just does not upload it.

**Comment by jasonculbertson** [comment]
Just freezes.  
![screen shot 2015-02-01 at 9 30 40 am](https://cloud.githubusercontent.com/assets/2825709/5993017/6786c35e-a9f6-11e4-92a4-1fc6cc89a01d.png)

**Comment by davidkarn** [comment]
The 16mb cutoff is set by mongodb and their doesn't seem to be an easy way around it, so I switched to storing file uploads on the disk. It's accepting any size file upload now, but making this change has broken all existing pictures and  message attachments, they will have to be re-uploaded
