### ISSUE TITLE
Update Apply Now page with tags for designers

### ISSUE THREAD

**Issue by jasonculbertson** [UseBento/UseBento#9]
Add 3 dropdowns in the Apply Now page.  These are optional.  Designs are coming for this.  Let me know if you need html for this @davidkarn.

![apply_now](https://cloud.githubusercontent.com/assets/2825709/5633053/9132cc2a-9588-11e4-9c09-484f13ddff73.png)

**Comment by davidkarn** [comment]
I added three dummy selects to the bottom of the apply page, using the .field class on the <select>'s. If the display on http://usebento.com/apply looks good, then we won't need HTML for this, just the values for the dropdown.

**Comment by jasonculbertson** [comment]
It's a bit broken on mobile but almost perfect. The second drop down is not
aligned correctly for some reason.

**Comment by jasonculbertson** [comment]
1. Copy above drop down fields “Which design skills are your strongest?”
2. Need logic for drop downs where user can’t have same thing selected for all 3 fields

**Comment by davidkarn** [comment]
Is it required that they fill in all three fields?

**Comment by jasonculbertson** [comment]
No.
